@startuml NextStep Class Diagram Entities Explicit

class Role {
  + id : number
  + name : string
}

class User {
  + id : number
  + email : string
  - password : string
  + firstName : string
  + lastName : string
  + isActive : boolean
  + createdAt : Date
  + updatedAt : Date
  + role : Role
}

class Skill {
  + id : number
  + name : string
}

class Seniority {
  + id : number
  + name : string
}

class JobOffer {
  + id : number
  + title : string
  + description : string
  + isActive : boolean
  + createdAt : Date
  + updatedAt : Date
  + recruiter : User
  + seniority : Seniority
  + skills : Skill[]
}

class Stage {
  + id : number
  + name : string
  + sequenceOrder : number
}

class Application {
  + id : number
  + appliedAt : Date
  + updatedAt : Date
  + applicant : User
  + jobOffer : JobOffer
  + currentStage : Stage
  + feedbacks : Feedback[]
}

class Feedback {
  + id : number
  + technicalScore : number | null
  + softSkillsScore : number | null
  + comment : string
  + createdAt : Date
  + application : Application
  + stage : Stage
}

class AuditLog {
  + id : number
  + action : string
  + tableName : string
  + recordId : string
  + metadata : any
  + createdAt : Date
  + user : User
}

' Flechas visuales para conectar el mapa
User "many" --> "1" Role
JobOffer "many" --> "1" User
JobOffer "many" --> "1" Seniority
JobOffer "many" --> "many" Skill

Application "many" --> "1" User
Application "many" --> "1" JobOffer
Application "many" --> "1" Stage

Application "1" *-- "many" Feedback
Feedback "many" --> "1" Stage
Feedback "many" --> "1" User

AuditLog "many" --> "1" User

@enduml