@startwbs Nexstep MVP WBS
* NextStep MVP WBS

** Configuración inicial del proyecto

*** Repositorio y entorno
**** Crear repositorio GitHub
**** Definir estructura de carpetas frontend / backend
**** Documentar instalación inicial en README

*** Backend base NestJS
**** Crear proyecto NestJS
**** Configurar módulos principales
**** Configurar TypeORM + PostgreSQL
**** Configurar Swagger

*** Frontend base NextJS
**** Crear proyecto NextJS con TypeScript
**** Configurar TailwindCSS
**** Definir estructura de páginas y componentes
**** Configurar cliente HTTP

** Autenticación y usuarios

*** Backend
**** Crear entidad User
**** Definir roles ADMIN / RECRUITER / APPLICANT
**** Endpoint registro

*** Administración
**** CRUD usuarios básico para Admin

*** Frontend
**** Página Login
**** Página Registro
**** Redirección según rol
**** Menú dinámico por perfil

** Módulo Vacantes

*** Backend
**** Crear entidad JobOffer
**** CRUD vacantes
**** Validar que recruiter solo crea, edita y elimina sus vacantes
**** Listar vacantes activas

*** Frontend Recruiter
**** Dashboard recruiter
**** Formulario crear vacante
**** Listado de mis vacantes
**** Editar / cerrar (actualiza estado) vacante

*** Frontend Candidato
**** Página listado de vacantes
**** Vista detalle vacante

** Módulo Postulaciones

*** Backend
**** Crear entidad Postulación
**** Endpoint postularse a vacante
**** Endpoint listar postulantes por vacante
**** Endpoint cambiar estado postulación

*** Frontend Recruiter
**** Página postulantes por vacante
**** Cambiar estado candidato

*** Frontend Candidato
**** Página mis postulaciones
**** Visualizar estado del proceso

** Módulo Feedback

*** Backend
**** Crear entidad Feedback
**** Endpoint crear feedback recruiter (POST)
**** Endpoint ver feedback candidato(GET)

*** Frontend Recruiter
**** Formulario cargar feedback

*** Frontend Candidato
**** Página mi feedback
**** Ver puntaje técnico
**** Ver puntaje soft skills
**** Ver comentario general

** Dashboard y perfiles

*** Candidato
**** Página perfil candidato
**** Dashboard con postulaciones + estados + feedback

*** Recruiter
**** Página perfil recruiter
**** Dashboard resumen vacantes + postulantes (números)

** Testing y ajustes finales

*** Backend
**** Test endpoints principales
**** Validaciones y manejo de errores

*** Frontend
**** Probar navegación general
**** Validar formularios

*** Integración
**** Pruebas frontend + backend
**** Corrección de bugs
**** Responsive básico

** Deploy y entrega final

*** Deploy
**** Deploy backend
**** Deploy frontend

*** Documentación
**** README final
**** Swagger actualizado
**** Informe técnico breve (incluye documento funcional, no funcional técnico, de arquitectura C4model )

@endwbs
